/**
 * CMS config assembler (spec 0.2 / 0.4).
 *
 * Runs at build (prebuild hook) with Node's native TS support (type-stripping,
 * default in Node >= 22.18 — see NOTES.md). Two jobs:
 *
 *   1. Compose public/admin/config.yml from the base config + every tier-2
 *      block's schema.ts fragment. Schema and component share a folder, so a
 *      block's editing UI can never drift from its rendered output.
 *   2. Vendor the Sveltia browser bundle into public/admin so /admin loads it
 *      from same-origin ('self') — no CDN, keeping the CSP tight.
 *
 * Fragments are discovered by scanning components/blocks/<Name>/schema.ts.
 * Each exports a BlockSchema as default. With zero blocks (pre-0.4) the page
 * body still gets a well-formed, empty list widget.
 */
import { readdir, readFile, writeFile, copyFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { pathToFileURL, fileURLToPath } from "node:url";
import { stringify as toYaml } from "yaml";
import type { BlockSchema } from "../lib/cms/types.ts";
import { baseConfig, siteFileCollection } from "../lib/cms/base-config.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const BLOCKS_DIR = join(ROOT, "components", "blocks");
const ADMIN_DIR = join(ROOT, "public", "admin");
const SVELTIA_SRC = join(
  ROOT,
  "node_modules",
  "@sveltia",
  "cms",
  "dist",
  "sveltia-cms.js",
);

async function discoverBlockSchemas(): Promise<BlockSchema[]> {
  let entries: string[] = [];
  try {
    entries = await readdir(BLOCKS_DIR);
  } catch {
    return [];
  }
  const schemas: BlockSchema[] = [];
  for (const name of entries.sort()) {
    const schemaPath = join(BLOCKS_DIR, name, "schema.ts");
    try {
      await readFile(schemaPath); // existence check
    } catch {
      continue; // not a block folder (e.g. README.md)
    }
    const mod = await import(pathToFileURL(schemaPath).href);
    const schema: BlockSchema | undefined = mod.default ?? mod.schema;
    if (!schema) {
      throw new Error(`${schemaPath} has no default BlockSchema export`);
    }
    schemas.push(schema);
  }
  return schemas;
}

/** A block fragment becomes one typed variant of the page "blocks" list. */
function blockToListType(block: BlockSchema) {
  return {
    name: block.name,
    label: block.label,
    ...(block.summary ? { summary: block.summary } : {}),
    widget: "object",
    fields: block.fields,
  };
}

function buildPagesCollection(blocks: BlockSchema[]) {
  return {
    name: "pages",
    label: "Pages",
    folder: "content/pages",
    create: true,
    extension: "md",
    format: "frontmatter",
    slug: "{{slug}}",
    fields: [
      { name: "title", label: "Title", widget: "string" },
      {
        name: "description",
        label: "Description",
        widget: "string",
        required: false,
      },
      {
        name: "slug",
        label: "URL slug",
        widget: "string",
        required: false,
        hint: 'Leave blank to derive from filename. "home" maps to /.',
      },
      {
        name: "blocks",
        label: "Content blocks",
        widget: "list",
        // typeKey defaults to "type" — matches BlockInstance.type in frontmatter.
        types: blocks.map(blockToListType),
      },
    ],
  };
}

async function main() {
  const blocks = await discoverBlockSchemas();

  const config = {
    ...baseConfig,
    collections: [buildPagesCollection(blocks), siteFileCollection],
  };

  await mkdir(ADMIN_DIR, { recursive: true });

  const header =
    "# GENERATED by scripts/build-cms-config.mts — do not edit by hand.\n" +
    "# Edit block schema.ts fragments or lib/cms/base-config.ts instead.\n\n";
  await writeFile(join(ADMIN_DIR, "config.yml"), header + toYaml(config), "utf8");

  await copyFile(SVELTIA_SRC, join(ADMIN_DIR, "sveltia-cms.js"));

  console.log(
    `[cms:config] wrote config.yml with ${blocks.length} block type(s): ` +
      `${blocks.map((b) => b.name).join(", ") || "(none yet)"}`,
  );
  console.log("[cms:config] vendored sveltia-cms.js into public/admin");
}

main().catch((err) => {
  console.error("[cms:config] failed:", err);
  process.exit(1);
});
